function v3_export_csv(t,y,file)
% CSV is a decimated view. Complete raw samples remain in MAT.
names={'time_s','Qref_mL_s','Qvalve_mL_s','Vbladder_mL','discharged_mL','contact_generalized_force_N', ...
 'command_STEP_s','raw_command_STEP_s','cable_x_m','actual_v_m_s','valve_closed','tail_mL_s','tail_drained_mL', ...
 'collected_mL','tracking_error_mL_s','command_acceleration_STEP_s2','integral_command_STEP_s','q0_mL_s','tclose_s', ...
 'outlet_mL_s','valve_latch','volume_comparator','target_saturation_flag','slew_flag','electrical_phase_rad', ...
 'torque_Nm','actual_omega_rad_s','cable_tension_N','guard_violation_count','first_failed_guard','independent_intQ_mL', ...
 'command_count_STEP','actual_acceleration_m_s2','guard_phase_rad','guard_travel_m','guard_volume_m3','guard_extension_m', ...
 'guard_speed_rad_s','guard_tension_N','guard_forward_flow_m3_s','signed_overlap_m','bladder_pressure_Pa','V_est_mL', ...
 'quiet_dwell_s','normal_done','terminal_stop_request','quiet'};
[~,idx]=unique(floor(t/.005),'stable');early=find(t<=3);[~,j]=unique(floor(t(early)/.0005),'stable');idx=[idx;early(j)];
tc=t(find(y(:,10)>.5,1));if ~isempty(tc),idx=[idx;find(abs(t-tc)<=.05)];end
for col=[2 5 6 9 24 25 26 27 32 40 41]
 [~,a]=max(y(:,col));[~,b]=min(y(:,col));idx=[idx;a;b]; %#ok<AGROW>
end
idx=unique([idx;1;numel(t)]);writetable(array2table([t(idx) y(idx,:)],'VariableNames',names),file);
end
